### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by josefs** [ocharles/monad-yield#1]
In order to build the project I had to get the transformers repo and put it next to this one. I also ran cabal2nix in the transformers repo. Then I could actually start building things. So these two steps would be useful to have in the readme.

But the build doesn't succeed for me. I get:

```
TransformersInline.hs:9:1:
    Failed to load interface for `Control.Monad.Trans.Reader'
    Perhaps you meant
      Control.Monad.Trans.Reader (from transformers-0.5.1.0)
      Control.Monad.Trans.Reader (needs flag -package-key transformers-0.4.2.0)
      Control.Monad.Trans.State (from transformers-0.5.1.0)

TransformersInline.hs:10:1:
    Failed to load interface for `Control.Monad.Trans.State.Lazy'
    Perhaps you meant
      Control.Monad.Trans.State.Lazy (from transformers-0.5.1.0)
      Control.Monad.Trans.State.Lazy (needs flag -package-key transformers-0.4.2.0)
      Control.Monad.Trans.Writer.Lazy (from transformers-0.5.1.0)

```

**Comment by ocharles** [comment]
What GHC? This project is not really intended for public consumption, either - so I'm hesistant to do the work on a README (I may well just throw all of this away, it's shared only because some people wanted to see the code.)

**Comment by josefs** [comment]
I believe GHC is 7.10.3 if I'm reading the verbose output from nix-build right.

**Comment by ocharles** [comment]
This was nothing more than a brief idea, so I'm going to close this as I'm not working on it anymore.

**Comment by josefs** [comment]
Sure.
